### ISSUE TITLE
Placeholder labels are not rendered

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-seo#156]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Version: Neos 5.3

### What you did
The placeholder for the creator for instance is not rendered correct. It worked for neos 4.3 and in 5.3 for instance it is just an i18n

### Expected Behavior
Renders placeholder label

### Actual Behavior
![Screenshot 2021-05-19 at 18 09 34](https://user-images.githubusercontent.com/1014126/118847883-80496700-b8ce-11eb-8c9a-dfea109bd72f.png)

**Comment by markusguenther** [comment]
Ok seems that this is an issue with the neos-ui.
Need to open an issue there and investigate whats wrong with the TextFieldEditor.

**Comment by Sebobo** [comment]
I already did some research on that and I think there is an open issue. The configuration is merged in wrong order since Neos 5.x or so for that individual case.
There was no quick fix at the time that I could come up with which wouldn't break yet another thing. We can take a look together some time if you want.

**Comment by Sebobo** [comment]
See https://github.com/neos/neos-development-collection/issues/3249
